// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: CodecLibraryBuilder
// **************************************************************************

const kThemeEncoders = <String, String>{
  'ActionIconThemeData': 'ThemeEncoder.encodeActionIconThemeData',
  'Alignment': 'ThemeEncoder.encodeAlignment',
  'AlignmentDirectional': 'ThemeEncoder.encodeAlignmentDirectional',
  'AlignmentGeometry': 'ThemeEncoder.encodeAlignmentGeometry',
  'AndroidOverscrollIndicator': 'ThemeEncoder.encodeAndroidOverscrollIndicator',
  'AppBarTheme': 'ThemeEncoder.encodeAppBarTheme',
  'AutovalidateMode': 'ThemeEncoder.encodeAutovalidateMode',
  'Axis': 'ThemeEncoder.encodeAxis',
  'BadgeThemeData': 'ThemeEncoder.encodeBadgeThemeData',
  'BlendMode': 'ThemeEncoder.encodeBlendMode',
  'BlurStyle': 'ThemeEncoder.encodeBlurStyle',
  'BorderRadius': 'ThemeEncoder.encodeBorderRadius',
  'BorderSide': 'ThemeEncoder.encodeBorderSide',
  'BorderStyle': 'ThemeEncoder.encodeBorderStyle',
  'BottomAppBarTheme': 'ThemeEncoder.encodeBottomAppBarTheme',
  'BottomNavigationBarThemeData':
      'ThemeEncoder.encodeBottomNavigationBarThemeData',
  'BottomNavigationBarLandscapeLayout':
      'ThemeEncoder.encodeBottomNavigationBarLandscapeLayout',
  'BottomNavigationBarType': 'ThemeEncoder.encodeBottomNavigationBarType',
  'BottomSheetThemeData': 'ThemeEncoder.encodeBottomSheetThemeData',
  'BoxBorder': 'ThemeEncoder.encodeBoxBorder',
  'BoxConstraints': 'ThemeEncoder.encodeBoxConstraints',
  'BoxDecoration': 'ThemeEncoder.encodeBoxDecoration',
  'BoxFit': 'ThemeEncoder.encodeBoxFit',
  'BoxHeightStyle': 'ThemeEncoder.encodeBoxHeightStyle',
  'BoxShadow': 'ThemeEncoder.encodeBoxShadow',
  'BoxShape': 'ThemeEncoder.encodeBoxShape',
  'BoxWidthStyle': 'ThemeEncoder.encodeBoxWidthStyle',
  'Brightness': 'ThemeEncoder.encodeBrightness',
  'ButtonBarLayoutBehavior': 'ThemeEncoder.encodeButtonBarLayoutBehavior',
  'ButtonBarThemeData': 'ThemeEncoder.encodeButtonBarThemeData',
  'ButtonStyle': 'ThemeEncoder.encodeButtonStyle',
  'ButtonTextTheme': 'ThemeEncoder.encodeButtonTextTheme',
  'ButtonThemeData': 'ThemeEncoder.encodeButtonThemeData',
  'CardTheme': 'ThemeEncoder.encodeCardTheme',
  'CheckboxThemeData': 'ThemeEncoder.encodeCheckboxThemeData',
  'ChipThemeData': 'ThemeEncoder.encodeChipThemeData',
  'Clip': 'ThemeEncoder.encodeClip',
  'Color': 'ThemeEncoder.encodeColor',
  'ColorScheme': 'ThemeEncoder.encodeColorScheme',
  'CrossAxisAlignment': 'ThemeEncoder.encodeCrossAxisAlignment',
  'CrossFadeState': 'ThemeEncoder.encodeCrossFadeState',
  'CupertinoTextThemeData': 'ThemeEncoder.encodeCupertinoTextThemeData',
  'CupertinoThemeData': 'ThemeEncoder.encodeCupertinoThemeData',
  'DatePickerThemeData': 'ThemeEncoder.encodeDatePickerThemeData',
  'DataTableThemeData': 'ThemeEncoder.encodeDataTableThemeData',
  'DecorationImage': 'ThemeEncoder.encodeDecorationImage',
  'DecorationPosition': 'ThemeEncoder.encodeDecorationPosition',
  'DialogTheme': 'ThemeEncoder.encodeDialogTheme',
  'DividerThemeData': 'ThemeEncoder.encodeDividerThemeData',
  'DragStartBehavior': 'ThemeEncoder.encodeDragStartBehavior',
  'DrawerThemeData': 'ThemeEncoder.encodeDrawerThemeData',
  'DropdownMenuThemeData': 'ThemeEncoder.encodeDropdownMenuThemeData',
  'EdgeInsets': 'ThemeEncoder.encodeEdgeInsets',
  'EdgeInsetsDirectional': 'ThemeEncoder.encodeEdgeInsetsDirectional',
  'EdgeInsetsGeometry': 'ThemeEncoder.encodeEdgeInsetsGeometry',
  'ElevatedButtonThemeData': 'ThemeEncoder.encodeElevatedButtonThemeData',
  'ExpansionTileThemeData': 'ThemeEncoder.encodeExpansionTileThemeData',
  'FilledButtonThemeData': 'ThemeEncoder.encodeFilledButtonThemeData',
  'FilterQuality': 'ThemeEncoder.encodeFilterQuality',
  'FlexFit': 'ThemeEncoder.encodeFlexFit',
  'FloatingActionButtonAnimator':
      'ThemeEncoder.encodeFloatingActionButtonAnimator',
  'FloatingActionButtonLocation':
      'ThemeEncoder.encodeFloatingActionButtonLocation',
  'FloatingActionButtonThemeData':
      'ThemeEncoder.encodeFloatingActionButtonThemeData',
  'FloatingLabelAlignment': 'ThemeEncoder.encodeFloatingLabelAlignment',
  'FloatingLabelBehavior': 'ThemeEncoder.encodeFloatingLabelBehavior',
  'FontFeature': 'ThemeEncoder.encodeFontFeature',
  'FontStyle': 'ThemeEncoder.encodeFontStyle',
  'FontWeight': 'ThemeEncoder.encodeFontWeight',
  'FontVariation': 'ThemeEncoder.encodeFontVariation',
  'Gradient': 'ThemeEncoder.encodeGradient',
  'GradientTransform': 'ThemeEncoder.encodeGradientTransform',
  'HitTestBehavior': 'ThemeEncoder.encodeHitTestBehavior',
  'Icon': 'ThemeEncoder.encodeIcon',
  'IconButtonThemeData': 'ThemeEncoder.encodeIconButtonThemeData',
  'IconData': 'ThemeEncoder.encodeIconData',
  'IconThemeData': 'ThemeEncoder.encodeIconThemeData',
  'ImageProvider': 'ThemeEncoder.encodeImageProvider',
  'ImageRepeat': 'ThemeEncoder.encodeImageRepeat',
  'InputBorder': 'ThemeEncoder.encodeInputBorder',
  'InputDecorationTheme': 'ThemeEncoder.encodeInputDecorationTheme',
  'InteractiveInkFeatureFactory':
      'ThemeEncoder.encodeInteractiveInkFeatureFactory',
  'ListTileStyle': 'ThemeEncoder.encodeListTileStyle',
  'ListTileTitleAlignment': 'ThemeEncoder.encodeListTileTitleAlignment',
  'ListTileThemeData': 'ThemeEncoder.encodeListTileThemeData',
  'Locale': 'ThemeEncoder.encodeLocale',
  'MainAxisAlignment': 'ThemeEncoder.encodeMainAxisAlignment',
  'MainAxisSize': 'ThemeEncoder.encodeMainAxisSize',
  'MaterialBannerThemeData': 'ThemeEncoder.encodeMaterialBannerThemeData',
  'MaterialColor': 'ThemeEncoder.encodeMaterialColor',
  'MaterialTapTargetSize': 'ThemeEncoder.encodeMaterialTapTargetSize',
  'MaterialType': 'ThemeEncoder.encodeMaterialType',
  'Matrix4': 'ThemeEncoder.encodeMatrix4',
  'MaxLengthEnforcement': 'ThemeEncoder.encodeMaxLengthEnforcement',
  'MenuBarThemeData': 'ThemeEncoder.encodeMenuBarThemeData',
  'MenuButtonThemeData': 'ThemeEncoder.encodeMenuButtonThemeData',
  'MenuStyle': 'ThemeEncoder.encodeMenuStyle',
  'MenuThemeData': 'ThemeEncoder.encodeMenuThemeData',
  'MouseCursor': 'ThemeEncoder.encodeMouseCursor',
  'NavigationBarThemeData': 'ThemeEncoder.encodeNavigationBarThemeData',
  'NavigationDestinationLabelBehavior':
      'ThemeEncoder.encodeNavigationDestinationLabelBehavior',
  'NavigationRailLabelType': 'ThemeEncoder.encodeNavigationRailLabelType',
  'NavigationRailThemeData': 'ThemeEncoder.encodeNavigationRailThemeData',
  'NotchedShape': 'ThemeEncoder.encodeNotchedShape',
  'Offset': 'ThemeEncoder.encodeOffset',
  'OrdinalSortKey': 'ThemeEncoder.encodeOrdinalSortKey',
  'OutlinedBorder': 'ThemeEncoder.encodeOutlinedBorder',
  'OutlinedButtonThemeData': 'ThemeEncoder.encodeOutlinedButtonThemeData',
  'OverflowBoxFit': 'ThemeEncoder.encodeOverflowBoxFit',
  'PageTransitionsBuilder': 'ThemeEncoder.encodePageTransitionsBuilder',
  'PageTransitionsTheme': 'ThemeEncoder.encodePageTransitionsTheme',
  'PanAxis': 'ThemeEncoder.encodePanAxis',
  'PointerDeviceKind': 'ThemeEncoder.encodePointerDeviceKind',
  'PopupMenuPosition': 'ThemeEncoder.encodePopupMenuPosition',
  'PopupMenuThemeData': 'ThemeEncoder.encodePopupMenuThemeData',
  'ProgressIndicatorThemeData': 'ThemeEncoder.encodeProgressIndicatorThemeData',
  'RadioThemeData': 'ThemeEncoder.encodeRadioThemeData',
  'Radius': 'ThemeEncoder.encodeRadius',
  'RangeSliderThumbShape': 'ThemeEncoder.encodeRangeSliderThumbShape',
  'RangeSliderTickMarkShape': 'ThemeEncoder.encodeRangeSliderTickMarkShape',
  'RangeSliderTrackShape': 'ThemeEncoder.encodeRangeSliderTrackShape',
  'RangeSliderValueIndicatorShape':
      'ThemeEncoder.encodeRangeSliderValueIndicatorShape',
  'Rect': 'ThemeEncoder.encodeRect',
  'ScrollBehavior': 'ThemeEncoder.encodeScrollBehavior',
  'ScrollPhysics': 'ThemeEncoder.encodeScrollPhysics',
  'ScrollViewKeyboardDismissBehavior':
      'ThemeEncoder.encodeScrollViewKeyboardDismissBehavior',
  'ScrollbarOrientation': 'ThemeEncoder.encodeScrollbarOrientation',
  'ScrollbarThemeData': 'ThemeEncoder.encodeScrollbarThemeData',
  'SearchBarThemeData': 'ThemeEncoder.encodeSearchBarThemeData',
  'SearchViewThemeData': 'ThemeEncoder.encodeSearchViewThemeData',
  'SegmentedButtonThemeData': 'ThemeEncoder.encodeSegmentedButtonThemeData',
  'SemanticsTag': 'ThemeEncoder.encodeSemanticsTag',
  'Shadow': 'ThemeEncoder.encodeShadow',
  'ShapeBorder': 'ThemeEncoder.encodeShapeBorder',
  'ShowValueIndicator': 'ThemeEncoder.encodeShowValueIndicator',
  'Size': 'ThemeEncoder.encodeSize',
  'SliderComponentShape': 'ThemeEncoder.encodeSliderComponentShape',
  'SliderInteraction': 'ThemeEncoder.encodeSliderInteraction',
  'SliderThemeData': 'ThemeEncoder.encodeSliderThemeData',
  'SliderTickMarkShape': 'ThemeEncoder.encodeSliderTickMarkShape',
  'SliderTrackShape': 'ThemeEncoder.encodeSliderTrackShape',
  'SmartDashesType': 'ThemeEncoder.encodeSmartDashesType',
  'SmartQuotesType': 'ThemeEncoder.encodeSmartQuotesType',
  'SnackBarBehavior': 'ThemeEncoder.encodeSnackBarBehavior',
  'SnackBarThemeData': 'ThemeEncoder.encodeSnackBarThemeData',
  'StackFit': 'ThemeEncoder.encodeStackFit',
  'StrutStyle': 'ThemeEncoder.encodeStrutStyle',
  'SwitchThemeData': 'ThemeEncoder.encodeSwitchThemeData',
  'SystemUiOverlayStyle': 'ThemeEncoder.encodeSystemUiOverlayStyle',
  'TabAlignment': 'ThemeEncoder.encodeTabAlignment',
  'TabBarIndicatorSize': 'ThemeEncoder.encodeTabBarIndicatorSize',
  'TabBarTheme': 'ThemeEncoder.encodeTabBarTheme',
  'TableBorder': 'ThemeEncoder.encodeTableBorder',
  'TableColumnWidth': 'ThemeEncoder.encodeTableColumnWidth',
  'TargetPlatform': 'ThemeEncoder.encodeTargetPlatform',
  'TextAlign': 'ThemeEncoder.encodeTextAlign',
  'TextAlignVertical': 'ThemeEncoder.encodeTextAlignVertical',
  'TextBaseline': 'ThemeEncoder.encodeTextBaseline',
  'TextButtonThemeData': 'ThemeEncoder.encodeTextButtonThemeData',
  'TextCapitalization': 'ThemeEncoder.encodeTextCapitalization',
  'TextDecoration': 'ThemeEncoder.encodeTextDecoration',
  'TextDecorationStyle': 'ThemeEncoder.encodeTextDecorationStyle',
  'TextDirection': 'ThemeEncoder.encodeTextDirection',
  'TextInputAction': 'ThemeEncoder.encodeTextInputAction',
  'TextInputType': 'ThemeEncoder.encodeTextInputType',
  'TextHeightBehavior': 'ThemeEncoder.encodeTextHeightBehavior',
  'TextLeadingDistribution': 'ThemeEncoder.encodeTextLeadingDistribution',
  'TextOverflow': 'ThemeEncoder.encodeTextOverflow',
  'TextSelectionThemeData': 'ThemeEncoder.encodeTextSelectionThemeData',
  'TextSpan': 'ThemeEncoder.encodeTextSpan',
  'TextStyle': 'ThemeEncoder.encodeTextStyle',
  'TextTheme': 'ThemeEncoder.encodeTextTheme',
  'TextWidthBasis': 'ThemeEncoder.encodeTextWidthBasis',
  'ThemeData': 'ThemeEncoder.encodeThemeData',
  'TileMode': 'ThemeEncoder.encodeTileMode',
  'TimePickerThemeData': 'ThemeEncoder.encodeTimePickerThemeData',
  'ToggleButtonsThemeData': 'ThemeEncoder.encodeToggleButtonsThemeData',
  'TooltipThemeData': 'ThemeEncoder.encodeTooltipThemeData',
  'TooltipTriggerMode': 'ThemeEncoder.encodeTooltipTriggerMode',
  'Typography': 'ThemeEncoder.encodeTypography',
  'VerticalDirection': 'ThemeEncoder.encodeVerticalDirection',
  'VisualDensity': 'ThemeEncoder.encodeVisualDensity',
  'WidgetStateColor': 'ThemeEncoder.encodeWidgetStateColor',
  'WidgetStatePropertyBool': 'ThemeEncoder.encodeWidgetStatePropertyBool',
  'WidgetStatePropertyBorderSide':
      'ThemeEncoder.encodeWidgetStatePropertyBorderSide',
  'WidgetStatePropertyColor': 'ThemeEncoder.encodeWidgetStatePropertyColor',
  'WidgetStatePropertyDouble': 'ThemeEncoder.encodeWidgetStatePropertyDouble',
  'WidgetStatePropertyEdgeInsetsGeometry':
      'ThemeEncoder.encodeWidgetStatePropertyEdgeInsetsGeometry',
  'WidgetStatePropertyIconThemeData':
      'ThemeEncoder.encodeWidgetStatePropertyIconThemeData',
  'WidgetStatePropertyMouseCursor':
      'ThemeEncoder.encodeWidgetStatePropertyMouseCursor',
  'WidgetStatePropertyOutlinedBorder':
      'ThemeEncoder.encodeWidgetStatePropertyOutlinedBorder',
  'WidgetStatePropertySize': 'ThemeEncoder.encodeWidgetStatePropertySize',
  'WidgetStatePropertyTextStyle':
      'ThemeEncoder.encodeWidgetStatePropertyTextStyle',
  'WrapAlignment': 'ThemeEncoder.encodeWrapAlignment',
  'WrapCrossAlignment': 'ThemeEncoder.encodeWrapCrossAlignment',
};
