// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: CodecLibraryBuilder
// **************************************************************************

const kThemeDecoders = <String, String>{
  'Alignment': 'ThemeDecoder.decodeAlignment',
  'AlignmentDirectional': 'ThemeDecoder.decodeAlignmentDirectional',
  'AlignmentGeometry': 'ThemeDecoder.decodeAlignmentGeometry',
  'AndroidOverscrollIndicator': 'ThemeDecoder.decodeAndroidOverscrollIndicator',
  'AppBarTheme': 'ThemeDecoder.decodeAppBarTheme',
  'AutovalidateMode': 'ThemeDecoder.decodeAutovalidateMode',
  'Axis': 'ThemeDecoder.decodeAxis',
  'BadgeThemeData': 'ThemeDecoder.decodeBadgeThemeData',
  'BlendMode': 'ThemeDecoder.decodeBlendMode',
  'BlurStyle': 'ThemeDecoder.decodeBlurStyle',
  'BorderRadius': 'ThemeDecoder.decodeBorderRadius',
  'BorderRadiusGeometry': 'ThemeDecoder.decodeBorderRadiusGeometry',
  'BorderSide': 'ThemeDecoder.decodeBorderSide',
  'BorderStyle': 'ThemeDecoder.decodeBorderStyle',
  'BottomAppBarTheme': 'ThemeDecoder.decodeBottomAppBarTheme',
  'BottomNavigationBarThemeData':
      'ThemeDecoder.decodeBottomNavigationBarThemeData',
  'BottomNavigationBarLandscapeLayout':
      'ThemeDecoder.decodeBottomNavigationBarLandscapeLayout',
  'BottomNavigationBarType': 'ThemeDecoder.decodeBottomNavigationBarType',
  'BottomSheetThemeData': 'ThemeDecoder.decodeBottomSheetThemeData',
  'BoxBorder': 'ThemeDecoder.decodeBoxBorder',
  'BoxConstraints': 'ThemeDecoder.decodeBoxConstraints',
  'BoxDecoration': 'ThemeDecoder.decodeBoxDecoration',
  'BoxFit': 'ThemeDecoder.decodeBoxFit',
  'BoxHeightStyle': 'ThemeDecoder.decodeBoxHeightStyle',
  'BoxShadow': 'ThemeDecoder.decodeBoxShadow',
  'BoxShape': 'ThemeDecoder.decodeBoxShape',
  'BoxWidthStyle': 'ThemeDecoder.decodeBoxWidthStyle',
  'Brightness': 'ThemeDecoder.decodeBrightness',
  'ButtonBarLayoutBehavior': 'ThemeDecoder.decodeButtonBarLayoutBehavior',
  'ButtonBarThemeData': 'ThemeDecoder.decodeButtonBarThemeData',
  'ButtonStyle': 'ThemeDecoder.decodeButtonStyle',
  'ButtonTextTheme': 'ThemeDecoder.decodeButtonTextTheme',
  'ButtonThemeData': 'ThemeDecoder.decodeButtonThemeData',
  'CardTheme': 'ThemeDecoder.decodeCardTheme',
  'CheckboxThemeData': 'ThemeDecoder.decodeCheckboxThemeData',
  'ChipThemeData': 'ThemeDecoder.decodeChipThemeData',
  'Clip': 'ThemeDecoder.decodeClip',
  'Color': 'ThemeDecoder.decodeColor',
  'ColorFilter': 'ThemeDecoder.decodeColorFilter',
  'ColorScheme': 'ThemeDecoder.decodeColorScheme',
  'CrossAxisAlignment': 'ThemeDecoder.decodeCrossAxisAlignment',
  'CrossFadeState': 'ThemeDecoder.decodeCrossFadeState',
  'CupertinoTextThemeData': 'ThemeDecoder.decodeCupertinoTextThemeData',
  'CupertinoThemeData': 'ThemeDecoder.decodeCupertinoThemeData',
  'DatePickerThemeData': 'ThemeDecoder.decodeDatePickerThemeData',
  'DataTableThemeData': 'ThemeDecoder.decodeDataTableThemeData',
  'DecorationImage': 'ThemeDecoder.decodeDecorationImage',
  'DecorationPosition': 'ThemeDecoder.decodeDecorationPosition',
  'DialogTheme': 'ThemeDecoder.decodeDialogTheme',
  'DividerThemeData': 'ThemeDecoder.decodeDividerThemeData',
  'DragStartBehavior': 'ThemeDecoder.decodeDragStartBehavior',
  'DrawerThemeData': 'ThemeDecoder.decodeDrawerThemeData',
  'DropdownMenuThemeData': 'ThemeDecoder.decodeDropdownMenuThemeData',
  'EdgeInsets': 'ThemeDecoder.decodeEdgeInsets',
  'EdgeInsetsDirectional': 'ThemeDecoder.decodeEdgeInsetsDirectional',
  'EdgeInsetsGeometry': 'ThemeDecoder.decodeEdgeInsetsGeometry',
  'ElevatedButtonThemeData': 'ThemeDecoder.decodeElevatedButtonThemeData',
  'ExpansionTileThemeData': 'ThemeDecoder.decodeExpansionTileThemeData',
  'FilledButtonThemeData': 'ThemeDecoder.decodeFilledButtonThemeData',
  'FilterQuality': 'ThemeDecoder.decodeFilterQuality',
  'FlexFit': 'ThemeDecoder.decodeFlexFit',
  'FloatingActionButtonAnimator':
      'ThemeDecoder.decodeFloatingActionButtonAnimator',
  'FloatingActionButtonLocation':
      'ThemeDecoder.decodeFloatingActionButtonLocation',
  'FloatingActionButtonThemeData':
      'ThemeDecoder.decodeFloatingActionButtonThemeData',
  'FloatingLabelAlignment': 'ThemeDecoder.decodeFloatingLabelAlignment',
  'FloatingLabelBehavior': 'ThemeDecoder.decodeFloatingLabelBehavior',
  'FontFeature': 'ThemeDecoder.decodeFontFeature',
  'FontStyle': 'ThemeDecoder.decodeFontStyle',
  'FontWeight': 'ThemeDecoder.decodeFontWeight',
  'FontVariation': 'ThemeDecoder.decodeFontVariation',
  'Gradient': 'ThemeDecoder.decodeGradient',
  'GradientTransform': 'ThemeDecoder.decodeGradientTransform',
  'HitTestBehavior': 'ThemeDecoder.decodeHitTestBehavior',
  'Icon': 'ThemeDecoder.decodeIcon',
  'IconButtonThemeData': 'ThemeDecoder.decodeIconButtonThemeData',
  'IconData': 'ThemeDecoder.decodeIconData',
  'IconThemeData': 'ThemeDecoder.decodeIconThemeData',
  'ImageProvider': 'ThemeDecoder.decodeImageProvider',
  'ImageRepeat': 'ThemeDecoder.decodeImageRepeat',
  'InputBorder': 'ThemeDecoder.decodeInputBorder',
  'InputDecorationTheme': 'ThemeDecoder.decodeInputDecorationTheme',
  'InteractiveInkFeatureFactory':
      'ThemeDecoder.decodeInteractiveInkFeatureFactory',
  'ListTileStyle': 'ThemeDecoder.decodeListTileStyle',
  'ListTileTitleAlignment': 'ThemeDecoder.decodeListTileTitleAlignment',
  'ListTileThemeData': 'ThemeDecoder.decodeListTileThemeData',
  'Locale': 'ThemeDecoder.decodeLocale',
  'MainAxisAlignment': 'ThemeDecoder.decodeMainAxisAlignment',
  'MainAxisSize': 'ThemeDecoder.decodeMainAxisSize',
  'MaterialBannerThemeData': 'ThemeDecoder.decodeMaterialBannerThemeData',
  'MaterialColor': 'ThemeDecoder.decodeMaterialColor',
  'MaterialStateProperty<bool>': 'ThemeDecoder.decodeMaterialStatePropertyBool',
  'MaterialStateProperty<BorderSide>':
      'ThemeDecoder.decodeMaterialStatePropertyBorderSide',
  'MaterialStateProperty<Color>':
      'ThemeDecoder.decodeMaterialStatePropertyColor',
  'MaterialStateProperty<double>':
      'ThemeDecoder.decodeMaterialStatePropertyDouble',
  'MaterialStateProperty<EdgeInsetsGeometry>':
      'ThemeDecoder.decodeMaterialStatePropertyEdgeInsetsGeometry',
  'MaterialStateProperty<Icon>': 'ThemeDecoder.decodeMaterialStatePropertyIcon',
  'MaterialStateProperty<IconThemeData>':
      'ThemeDecoder.decodeMaterialStatePropertyIconThemeData',
  'MaterialStateProperty<MouseCursor>':
      'ThemeDecoder.decodeMaterialStatePropertyMouseCursor',
  'MaterialStateProperty<OutlinedBorder>':
      'ThemeDecoder.decodeMaterialStatePropertyOutlinedBorder',
  'MaterialStateProperty<Size>': 'ThemeDecoder.decodeMaterialStatePropertySize',
  'MaterialStateProperty<TextStyle>':
      'ThemeDecoder.decodeMaterialStatePropertyTextStyle',
  'MaterialTapTargetSize': 'ThemeDecoder.decodeMaterialTapTargetSize',
  'MaterialType': 'ThemeDecoder.decodeMaterialType',
  'Matrix4': 'ThemeDecoder.decodeMatrix4',
  'MaxLengthEnforcement': 'ThemeDecoder.decodeMaxLengthEnforcement',
  'MenuBarThemeData': 'ThemeDecoder.decodeMenuBarThemeData',
  'MenuButtonThemeData': 'ThemeDecoder.decodeMenuButtonThemeData',
  'MenuStyle': 'ThemeDecoder.decodeMenuStyle',
  'MenuThemeData': 'ThemeDecoder.decodeMenuThemeData',
  'MouseCursor': 'ThemeDecoder.decodeMouseCursor',
  'NavigationBarThemeData': 'ThemeDecoder.decodeNavigationBarThemeData',
  'NavigationDestinationLabelBehavior':
      'ThemeDecoder.decodeNavigationDestinationLabelBehavior',
  'NavigationDrawerThemeData': 'ThemeDecoder.decodeNavigationDrawerThemeData',
  'NavigationRailLabelType': 'ThemeDecoder.decodeNavigationRailLabelType',
  'NavigationRailThemeData': 'ThemeDecoder.decodeNavigationRailThemeData',
  'NotchedShape': 'ThemeDecoder.decodeNotchedShape',
  'Offset': 'ThemeDecoder.decodeOffset',
  'OrdinalSortKey': 'ThemeDecoder.decodeOrdinalSortKey',
  'OutlinedBorder': 'ThemeDecoder.decodeOutlinedBorder',
  'OutlinedButtonThemeData': 'ThemeDecoder.decodeOutlinedButtonThemeData',
  'PageTransitionsBuilder': 'ThemeDecoder.decodePageTransitionsBuilder',
  'PageTransitionsTheme': 'ThemeDecoder.decodePageTransitionsTheme',
  'PanAxis': 'ThemeDecoder.decodePanAxis',
  'PointerDeviceKind': 'ThemeDecoder.decodePointerDeviceKind',
  'PopupMenuPosition': 'ThemeDecoder.decodePopupMenuPosition',
  'PopupMenuThemeData': 'ThemeDecoder.decodePopupMenuThemeData',
  'ProgressIndicatorThemeData': 'ThemeDecoder.decodeProgressIndicatorThemeData',
  'RadioThemeData': 'ThemeDecoder.decodeRadioThemeData',
  'Radius': 'ThemeDecoder.decodeRadius',
  'RangeSliderThumbShape': 'ThemeDecoder.decodeRangeSliderThumbShape',
  'RangeSliderTickMarkShape': 'ThemeDecoder.decodeRangeSliderTickMarkShape',
  'RangeSliderTrackShape': 'ThemeDecoder.decodeRangeSliderTrackShape',
  'RangeSliderValueIndicatorShape':
      'ThemeDecoder.decodeRangeSliderValueIndicatorShape',
  'Rect': 'ThemeDecoder.decodeRect',
  'ScrollBehavior': 'ThemeDecoder.decodeScrollBehavior',
  'ScrollPhysics': 'ThemeDecoder.decodeScrollPhysics',
  'ScrollViewKeyboardDismissBehavior':
      'ThemeDecoder.decodeScrollViewKeyboardDismissBehavior',
  'ScrollbarOrientation': 'ThemeDecoder.decodeScrollbarOrientation',
  'ScrollbarThemeData': 'ThemeDecoder.decodeScrollbarThemeData',
  'SearchBarThemeData': 'ThemeDecoder.decodeSearchBarThemeData',
  'SearchViewThemeData': 'ThemeDecoder.decodeSearchViewThemeData',
  'SegmentedButtonThemeData': 'ThemeDecoder.decodeSegmentedButtonThemeData',
  'SemanticsTag': 'ThemeDecoder.decodeSemanticsTag',
  'Shadow': 'ThemeDecoder.decodeShadow',
  'ShapeBorder': 'ThemeDecoder.decodeShapeBorder',
  'ShowValueIndicator': 'ThemeDecoder.decodeShowValueIndicator',
  'Size': 'ThemeDecoder.decodeSize',
  'SliderComponentShape': 'ThemeDecoder.decodeSliderComponentShape',
  'SliderThemeData': 'ThemeDecoder.decodeSliderThemeData',
  'SliderTickMarkShape': 'ThemeDecoder.decodeSliderTickMarkShape',
  'SliderTrackShape': 'ThemeDecoder.decodeSliderTrackShape',
  'SmartDashesType': 'ThemeDecoder.decodeSmartDashesType',
  'SmartQuotesType': 'ThemeDecoder.decodeSmartQuotesType',
  'SnackBarBehavior': 'ThemeDecoder.decodeSnackBarBehavior',
  'SnackBarThemeData': 'ThemeDecoder.decodeSnackBarThemeData',
  'StackFit': 'ThemeDecoder.decodeStackFit',
  'StrutStyle': 'ThemeDecoder.decodeStrutStyle',
  'SwitchThemeData': 'ThemeDecoder.decodeSwitchThemeData',
  'SystemUiOverlayStyle': 'ThemeDecoder.decodeSystemUiOverlayStyle',
  'TabBarIndicatorSize': 'ThemeDecoder.decodeTabBarIndicatorSize',
  'TabBarTheme': 'ThemeDecoder.decodeTabBarTheme',
  'TableBorder': 'ThemeDecoder.decodeTableBorder',
  'TableColumnWidth': 'ThemeDecoder.decodeTableColumnWidth',
  'TargetPlatform': 'ThemeDecoder.decodeTargetPlatform',
  'TextAlign': 'ThemeDecoder.decodeTextAlign',
  'TextAlignVertical': 'ThemeDecoder.decodeTextAlignVertical',
  'TextBaseline': 'ThemeDecoder.decodeTextBaseline',
  'TextButtonThemeData': 'ThemeDecoder.decodeTextButtonThemeData',
  'TextCapitalization': 'ThemeDecoder.decodeTextCapitalization',
  'TextDecoration': 'ThemeDecoder.decodeTextDecoration',
  'TextDecorationStyle': 'ThemeDecoder.decodeTextDecorationStyle',
  'TextDirection': 'ThemeDecoder.decodeTextDirection',
  'TextHeightBehavior': 'ThemeDecoder.decodeTextHeightBehavior',
  'TextInputAction': 'ThemeDecoder.decodeTextInputAction',
  'TextInputType': 'ThemeDecoder.decodeTextInputType',
  'TextLeadingDistribution': 'ThemeDecoder.decodeTextLeadingDistribution',
  'TextOverflow': 'ThemeDecoder.decodeTextOverflow',
  'TextSelectionThemeData': 'ThemeDecoder.decodeTextSelectionThemeData',
  'TextSpan': 'ThemeDecoder.decodeTextSpan',
  'TextStyle': 'ThemeDecoder.decodeTextStyle',
  'TextTheme': 'ThemeDecoder.decodeTextTheme',
  'TextWidthBasis': 'ThemeDecoder.decodeTextWidthBasis',
  'ThemeData': 'ThemeDecoder.decodeThemeData',
  'TileMode': 'ThemeDecoder.decodeTileMode',
  'TimePickerThemeData': 'ThemeDecoder.decodeTimePickerThemeData',
  'ToggleButtonsThemeData': 'ThemeDecoder.decodeToggleButtonsThemeData',
  'TooltipThemeData': 'ThemeDecoder.decodeTooltipThemeData',
  'TooltipTriggerMode': 'ThemeDecoder.decodeTooltipTriggerMode',
  'Typography': 'ThemeDecoder.decodeTypography',
  'VerticalDirection': 'ThemeDecoder.decodeVerticalDirection',
  'VisualDensity': 'ThemeDecoder.decodeVisualDensity',
  'WrapAlignment': 'ThemeDecoder.decodeWrapAlignment',
  'WrapCrossAlignment': 'ThemeDecoder.decodeWrapCrossAlignment',
};
