import 'all.dart';

class Schemas {
  static final all = <String, Map<String, Object>>{
    ActionIconThemeDataSchema.id: ActionIconThemeDataSchema.schema,
    AlignmentDirectionalSchema.id: AlignmentDirectionalSchema.schema,
    AlignmentGeometrySchema.id: AlignmentGeometrySchema.schema,
    AlignmentSchema.id: AlignmentSchema.schema,
    AndroidOverscrollIndicatorSchema.id:
        AndroidOverscrollIndicatorSchema.schema,
    AnimationStyleSchema.id: AnimationStyleSchema.schema,
    AppBarThemeSchema.id: AppBarThemeSchema.schema,
    AutovalidateModeSchema.id: AutovalidateModeSchema.schema,
    AxisSchema.id: AxisSchema.schema,
    BadgeThemeDataSchema.id: BadgeThemeDataSchema.schema,
    BlendModeSchema.id: BlendModeSchema.schema,
    BlurStyleSchema.id: BlurStyleSchema.schema,
    BorderRadiusGeometrySchema.id: BorderRadiusGeometrySchema.schema,
    BorderRadiusSchema.id: BorderRadiusSchema.schema,
    BorderSideSchema.id: BorderSideSchema.schema,
    BorderStyleSchema.id: BorderStyleSchema.schema,
    BottomAppBarThemeScheme.id: BottomAppBarThemeScheme.schema,
    BottomNavigationBarLandscapeLayoutSchema.id:
        BottomNavigationBarLandscapeLayoutSchema.schema,
    BottomNavigationBarThemeDataSchema.id:
        BottomNavigationBarThemeDataSchema.schema,
    BottomNavigationBarTypeSchema.id: BottomNavigationBarTypeSchema.schema,
    BottomSheetThemeDataSchema.id: BottomSheetThemeDataSchema.schema,
    BoxBorderSchema.id: BoxBorderSchema.schema,
    BoxConstraintsSchema.id: BoxConstraintsSchema.schema,
    BoxDecorationSchema.id: BoxDecorationSchema.schema,
    BoxFitSchema.id: BoxFitSchema.schema,
    BoxHeightStyleSchema.id: BoxHeightStyleSchema.schema,
    BoxShadowSchema.id: BoxShadowSchema.schema,
    BoxShapeSchema.id: BoxShapeSchema.schema,
    BoxWidthStyleSchema.id: BoxWidthStyleSchema.schema,
    BrightnessSchema.id: BrightnessSchema.schema,
    ButtonBarLayoutBehaviorSchema.id: ButtonBarLayoutBehaviorSchema.schema,
    ButtonBarThemeDataSchema.id: ButtonBarThemeDataSchema.schema,
    ButtonStyleSchema.id: ButtonStyleSchema.schema,
    ButtonTextThemeSchema.id: ButtonTextThemeSchema.schema,
    ButtonThemeDataSchema.id: ButtonThemeDataSchema.schema,
    CardThemeDataSchema.id: CardThemeDataSchema.schema,
    CheckboxThemeDataSchema.id: CheckboxThemeDataSchema.schema,
    ChipThemeDataSchema.id: ChipThemeDataSchema.schema,
    ClipSchema.id: ClipSchema.schema,
    ColorFilterSchema.id: ColorFilterSchema.schema,
    ColorSchema.id: ColorSchema.schema,
    ColorSchemeSchema.id: ColorSchemeSchema.schema,
    CrossAxisAlignmentSchema.id: CrossAxisAlignmentSchema.schema,
    CrossFadeStateSchema.id: CrossFadeStateSchema.schema,
    CupertinoTextThemeDataSchema.id: CupertinoTextThemeDataSchema.schema,
    CupertinoThemeDataSchema.id: CupertinoThemeDataSchema.schema,
    DatePickerThemeDataSchema.id: DatePickerThemeDataSchema.schema,
    DataTableThemeDataSchema.id: DataTableThemeDataSchema.schema,
    DecorationImageSchema.id: DecorationImageSchema.schema,
    DecorationPositionSchema.id: DecorationPositionSchema.schema,
    DialogThemeDataSchema.id: DialogThemeDataSchema.schema,
    DismissDirectionSchema.id: DismissDirectionSchema.schema,
    DividerThemeDataSchema.id: DividerThemeDataSchema.schema,
    DragStartBehaviorSchema.id: DragStartBehaviorSchema.schema,
    DrawerThemeDataSchema.id: DrawerThemeDataSchema.schema,
    DropdownMenuThemeDataSchema.id: DropdownMenuThemeDataSchema.schema,
    EdgeInsetsSchema.id: EdgeInsetsSchema.schema,
    EdgeInsetsDirectionalSchema.id: EdgeInsetsDirectionalSchema.schema,
    EdgeInsetsGeometrySchema.id: EdgeInsetsGeometrySchema.schema,
    ElevatedButtonThemeDataSchema.id: ElevatedButtonThemeDataSchema.schema,
    ExpansionTileThemeDataSchema.id: ExpansionTileThemeDataSchema.schema,
    FilledButtonThemeDataSchema.id: FilledButtonThemeDataSchema.schema,
    FilterQualitySchema.id: FilterQualitySchema.schema,
    FlexFitSchema.id: FlexFitSchema.schema,
    FloatingActionButtonAnimatorSchema.id:
        FloatingActionButtonAnimatorSchema.schema,
    FloatingActionButtonLocationSchema.id:
        FloatingActionButtonLocationSchema.schema,
    FloatingActionButtonThemeDataSchema.id:
        FloatingActionButtonThemeDataSchema.schema,
    FloatingLabelAlignmentSchema.id: FloatingLabelAlignmentSchema.schema,
    FloatingLabelBehaviorSchema.id: FloatingLabelBehaviorSchema.schema,
    FontFeatureSchema.id: FontFeatureSchema.schema,
    FontStyleSchema.id: FontStyleSchema.schema,
    FontWeightSchema.id: FontWeightSchema.schema,
    FontVariationSchema.id: FontVariationSchema.schema,
    GradientSchema.id: GradientSchema.schema,
    GradientTransformSchema.id: GradientTransformSchema.schema,
    HitTestBehaviorSchema.id: HitTestBehaviorSchema.schema,
    IconButtonThemeDataSchema.id: IconButtonThemeDataSchema.schema,
    IconSchema.id: IconSchema.schema,
    IconAlignmentSchema.id: IconAlignmentSchema.schema,
    IconDataSchema.id: IconDataSchema.schema,
    IconThemeDataSchema.id: IconThemeDataSchema.schema,
    ImageProviderSchema.id: ImageProviderSchema.schema,
    ImageRepeatSchema.id: ImageRepeatSchema.schema,
    InputBorderSchema.id: InputBorderSchema.schema,
    InputDecorationThemeSchema.id: InputDecorationThemeSchema.schema,
    InteractiveInkFeatureFactorySchema.id:
        InteractiveInkFeatureFactorySchema.schema,
    ListTileControlAffinitySchema.id: ListTileControlAffinitySchema.schema,
    ListTileStyleSchema.id: ListTileStyleSchema.schema,
    ListTileThemeDataSchema.id: ListTileThemeDataSchema.schema,
    ListTileTitleAlignmentSchema.id: ListTileTitleAlignmentSchema.schema,
    LocaleSchema.id: LocaleSchema.schema,
    MainAxisAlignmentSchema.id: MainAxisAlignmentSchema.schema,
    MainAxisSizeSchema.id: MainAxisSizeSchema.schema,
    MaterialBannerThemeDataSchema.id: MaterialBannerThemeDataSchema.schema,
    MaterialColorSchema.id: MaterialColorSchema.schema,
    MaterialTapTargetSizeSchema.id: MaterialTapTargetSizeSchema.schema,
    MaterialTypeSchema.id: MaterialTypeSchema.schema,
    Matrix4Schema.id: Matrix4Schema.schema,
    MaxLengthEnforcementSchema.id: MaxLengthEnforcementSchema.schema,
    MenuBarThemeDataSchema.id: MenuBarThemeDataSchema.schema,
    MenuButtonThemeDataSchema.id: MenuButtonThemeDataSchema.schema,
    MenuStyleSchema.id: MenuStyleSchema.schema,
    MenuThemeDataSchema.id: MenuThemeDataSchema.schema,
    MouseCursorSchema.id: MouseCursorSchema.schemas,
    NavigationBarThemeDataSchema.id: NavigationBarThemeDataSchema.schema,
    NavigationDestinationLabelBehaviorSchema.id:
        NavigationDestinationLabelBehaviorSchema.schema,
    NavigationDrawerThemeDataSchema.id: NavigationDrawerThemeDataSchema.schema,
    NavigationRailLabelTypeSchema.id: NavigationRailLabelTypeSchema.schema,
    NavigationRailThemeDataSchema.id: NavigationRailThemeDataSchema.schema,
    NotchedShapeSchema.id: NotchedShapeSchema.schema,
    OffsetSchema.id: OffsetSchema.schema,
    OrdinalSortKeySchema.id: OrdinalSortKeySchema.schema,
    OutlinedBorderSchema.id: OutlinedBorderSchema.schema,
    OutlinedButtonThemeDataSchema.id: OutlinedButtonThemeDataSchema.schema,
    OverflowBoxFitSchema.id: OverflowBoxFitSchema.schema,
    PanAxisSchema.id: PanAxisSchema.schema,
    PageTransitionsBuilderSchema.id: PageTransitionsBuilderSchema.schema,
    PageTransitionsThemeSchema.id: PageTransitionsThemeSchema.schema,
    PointerDeviceKindSchema.id: PointerDeviceKindSchema.schema,
    PopupMenuPositionSchema.id: PopupMenuPositionSchema.schema,
    PopupMenuThemeDataSchema.id: PopupMenuThemeDataSchema.schema,
    ProgressIndicatorThemeDataSchema.id:
        ProgressIndicatorThemeDataSchema.schema,
    RadioThemeDataSchema.id: RadioThemeDataSchema.schema,
    RadiusSchema.id: RadiusSchema.schema,
    RangeSliderThumbShapeSchema.id: RangeSliderThumbShapeSchema.schema,
    RangeSliderTickMarkShapeSchema.id: RangeSliderTickMarkShapeSchema.schema,
    RangeSliderTrackShapeSchema.id: RangeSliderTrackShapeSchema.schema,
    RangeSliderValueIndicatorShapeSchema.id:
        RangeSliderValueIndicatorShapeSchema.schema,
    RectSchema.id: RectSchema.schema,
    ScrollBehaviorSchema.id: ScrollBehaviorSchema.schema,
    ScrollPhysicsSchema.id: ScrollPhysicsSchema.schema,
    ScrollViewKeyboardDismissBehaviorSchema.id:
        ScrollViewKeyboardDismissBehaviorSchema.schema,
    ScrollbarOrientationSchema.id: ScrollbarOrientationSchema.schema,
    ScrollbarThemeDataSchema.id: ScrollbarThemeDataSchema.schema,
    SearchBarThemeDataSchema.id: SearchBarThemeDataSchema.schema,
    SearchViewThemeDataSchema.id: SearchViewThemeDataSchema.schema,
    SegmentedButtonThemeDataSchema.id: SegmentedButtonThemeDataSchema.schema,
    SemanticsTagSchema.id: SemanticsTagSchema.schema,
    ShadowSchema.id: ShadowSchema.schema,
    ShapeBorderSchema.id: ShapeBorderSchema.schema,
    ShowValueIndicatorSchema.id: ShowValueIndicatorSchema.schema,
    SizeSchema.id: SizeSchema.schema,
    SliderComponentShapeSchema.id: SliderComponentShapeSchema.schema,
    SliderInteractionSchema.id: SliderInteractionSchema.schema,
    SliderThemeDataSchema.id: SliderThemeDataSchema.schema,
    SliderTickMarkShapeSchema.id: SliderTickMarkShapeSchema.schema,
    SliderTrackShapeSchema.id: SliderTrackShapeSchema.schema,
    SmartDashesTypeSchema.id: SmartDashesTypeSchema.schema,
    SmartQuotesTypeSchema.id: SmartQuotesTypeSchema.schema,
    SnackBarBehaviorSchema.id: SnackBarBehaviorSchema.schema,
    SnackBarThemeDataSchema.id: SnackBarThemeDataSchema.schema,
    StackFitSchema.id: StackFitSchema.schema,
    StrokeCapSchema.id: StrokeCapSchema.schema,
    StrutStyleSchema.id: StrutStyleSchema.schema,
    SwitchThemeDataSchema.id: SwitchThemeDataSchema.schema,
    SystemUiOverlayStyleSchema.id: SystemUiOverlayStyleSchema.schema,
    TabAlignmentSchema.id: TabAlignmentSchema.schema,
    TabBarIndicatorSizeSchema.id: TabBarIndicatorSizeSchema.schema,
    TabBarThemeDataSchema.id: TabBarThemeDataSchema.schema,
    TabIndicatorAnimationSchema.id: TabIndicatorAnimationSchema.schema,
    TableBorderSchema.id: TableBorderSchema.schema,
    TableColumnWidthSchema.id: TableColumnWidthSchema.schema,
    TargetPlatformSchema.id: TargetPlatformSchema.schema,
    TextAlignSchema.id: TextAlignSchema.schema,
    TextAlignVerticalSchema.id: TextAlignVerticalSchema.schema,
    TextBaselineSchema.id: TextBaselineSchema.schema,
    TextButtonThemeDataSchema.id: TextButtonThemeDataSchema.schema,
    TextCapitalizationSchema.id: TextCapitalizationSchema.schema,
    TextDecorationSchema.id: TextDecorationSchema.schema,
    TextDecorationStyleSchema.id: TextDecorationStyleSchema.schema,
    TextDirectionSchema.id: TextDirectionSchema.schema,
    TextHeightBehaviorSchema.id: TextHeightBehaviorSchema.schema,
    TextInputActionSchema.id: TextInputActionSchema.schema,
    TextInputTypeSchema.id: TextInputTypeSchema.schema,
    TextLeadingDistributionSchema.id: TextLeadingDistributionSchema.schema,
    TextOverflowSchema.id: TextOverflowSchema.schema,
    TextScalerSchema.id: TextScalerSchema.schema,
    TextSelectionThemeDataSchema.id: TextSelectionThemeDataSchema.schema,
    TextSpanSchema.id: TextSpanSchema.schema,
    TextStyleSchema.id: TextStyleSchema.schema,
    TextThemeSchema.id: TextThemeSchema.schema,
    TextWidthBasisSchema.id: TextWidthBasisSchema.schema,
    ThemeDataSchema.id: ThemeDataSchema.schema,
    TileModeSchema.id: TileModeSchema.schema,
    TimePickerThemeDataSchema.id: TimePickerThemeDataSchema.schema,
    ToggleButtonsThemeDataSchema.id: ToggleButtonsThemeDataSchema.schema,
    TooltipThemeDataSchema.id: TooltipThemeDataSchema.schema,
    TooltipTriggerModeSchema.id: TooltipTriggerModeSchema.schema,
    TypographySchema.id: TypographySchema.schema,
    VerticalDirectionSchema.id: VerticalDirectionSchema.schema,
    VisualDensitySchema.id: VisualDensitySchema.schema,
    WidgetStateColorSchema.id: WidgetStateColorSchema.schema,
    WidgetStatePropertyBoolSchema.id: WidgetStatePropertyBoolSchema.schema,
    WidgetStatePropertyBorderSideSchema.id:
        WidgetStatePropertyBorderSideSchema.schema,
    WidgetStatePropertyColorSchema.id: WidgetStatePropertyColorSchema.schema,
    WidgetStatePropertyDoubleSchema.id: WidgetStatePropertyDoubleSchema.schema,
    WidgetStatePropertyEdgeInsetsGeometrySchema.id:
        WidgetStatePropertyEdgeInsetsGeometrySchema.schema,
    WidgetStatePropertyIconSchema.id: WidgetStatePropertyIconSchema.schema,
    WidgetStatePropertyIconThemeDataSchema.id:
        WidgetStatePropertyIconThemeDataSchema.schema,
    WidgetStatePropertyMouseCursorSchema.id:
        WidgetStatePropertyMouseCursorSchema.schema,
    WidgetStatePropertyOutlinedBorderSchema.id:
        WidgetStatePropertyOutlinedBorderSchema.schema,
    WidgetStatePropertySizeSchema.id: WidgetStatePropertySizeSchema.schema,
    WidgetStatePropertyTextStyleSchema.id:
        WidgetStatePropertyTextStyleSchema.schema,
    WrapAlignmentSchema.id: WrapAlignmentSchema.schema,
    WrapCrossAlignmentSchema.id: WrapCrossAlignmentSchema.schema,
  };
}
