import 'package:json_theme/json_theme_schemas.dart';

class ColorSchemeSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_theme/color_scheme.json';

  static final schema = {
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    r'$comment': 'https:api.flutter.devfluttermaterialColorScheme-class.html',
    'title': 'ColorScheme',
    'type': 'object',
    'properties': {
      'brightness': SchemaHelper.objectSchema(BrightnessSchema.id),
      'error': SchemaHelper.objectSchema(ColorSchema.id),
      'errorContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'inversePrimary': SchemaHelper.objectSchema(ColorSchema.id),
      'inverseSurface': SchemaHelper.objectSchema(ColorSchema.id),
      'onError': SchemaHelper.objectSchema(ColorSchema.id),
      'onErrorContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'onInverseSurface': SchemaHelper.objectSchema(ColorSchema.id),
      'onPrimaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'onPrimary': SchemaHelper.objectSchema(ColorSchema.id),
      'onPrimaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'onPrimaryFixedVariant': SchemaHelper.objectSchema(ColorSchema.id),
      'onSecondary': SchemaHelper.objectSchema(ColorSchema.id),
      'onSecondaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'onSecondaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'onSecondaryFixedVariant': SchemaHelper.objectSchema(ColorSchema.id),
      'onSurface': SchemaHelper.objectSchema(ColorSchema.id),
      'onSurfaceVariant': SchemaHelper.objectSchema(ColorSchema.id),
      'onTertiary': SchemaHelper.objectSchema(ColorSchema.id),
      'onTertiaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'onTertiaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'onTertiaryFixedVariant': SchemaHelper.objectSchema(ColorSchema.id),
      'outline': SchemaHelper.objectSchema(ColorSchema.id),
      'outlineVariant': SchemaHelper.objectSchema(ColorSchema.id),
      'primary': SchemaHelper.objectSchema(ColorSchema.id),
      'primaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'primaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'primaryFixedDim': SchemaHelper.objectSchema(ColorSchema.id),
      'scrim': SchemaHelper.objectSchema(ColorSchema.id),
      'secondary': SchemaHelper.objectSchema(ColorSchema.id),
      'secondaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'secondaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'secondaryFixedDim': SchemaHelper.objectSchema(ColorSchema.id),
      'shadow': SchemaHelper.objectSchema(ColorSchema.id),
      'surface': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceBright': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceContainerHighest': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceContainerHigh': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceContainerLow': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceContainerLowest': SchemaHelper.objectSchema(ColorSchema.id),
      'surfaceDim': SchemaHelper.objectSchema(ColorSchema.id),
      'tertiary': SchemaHelper.objectSchema(ColorSchema.id),
      'tertiaryContainer': SchemaHelper.objectSchema(ColorSchema.id),
      'tertiaryFixed': SchemaHelper.objectSchema(ColorSchema.id),
      'tertiaryFixedDim': SchemaHelper.objectSchema(ColorSchema.id)
    },
  };
}
