name: "json_theme_annotation"
description: "Simple package holding the annotations needed by the JsonTheme code generator."
homepage: "https://github.com/peiffer-innovations/json_theme"
version: "1.0.3+18"

environment:
  sdk: ">=3.0.0 <4.0.0"

analyzer:
  exclude:
    - "lib/generated/**"
    - "lib/**/*.g.dart"

dev_dependencies:
  flutter_lints: "^6.0.0"
  test: "^1.26.2"

permittedLicenses:
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "MIT"
  - "MIT-Modern-Variant"
  - "MPL-2.0"
  - "Zlib"

packageLicenseOverride:
  flutter: "BSD-3-Clause"
  flutter_driver: "BSD-3-Clause"
  flutter_goldens: "BSD-3-Clause"
  flutter_localizations: "BSD-3-Clause"
  flutter_web_plugins: "BSD-3-Clause"
  flutter_test: "BSD-3-Clause"
  fuchsia_remote_debug_protocol: "BSD-3-Clause"
  integration_test: "BSD-3-Clause"
  rxdart: "Apache-2.0"

ignore_updates:
  - "archive"
  - "async"
  - "boolean_selector"
  - "characters"
  - "charcode"
  - "collection"
  - "clock"
  - "crypto"
  - "fake_async"
  - "file"
  - "matcher"
  - "material_color_utilities"
  - "meta"
  - "path"
  - "source_span"
  - "stack_trace"
  - "stream_channel"
  - "string_scanner"
  - "sync_http"
  - "term_glyph"
  - "test_api"
  - "typed_data"
  - "uuid"
  - "vector_math"
  - "webdriver"
